Update dpm-advice-basic-melee.txt
pvme/pvme-guides pull request #4898
Opened 2023-05-26 20:00 UTC by Sky-Justice

Minor Changes: 
- Fixed bullet point formatting error under weapon breakdown. 
- Cleaned some redundant phrases
- Added a missing Dragon Rider Lance emoji to weapon breakdown

# PvME Change Submission
Thank you for helping maintain our resources! Below is a quick sanity checklist that helps make sure we can keep track of what is changing. Please fill it out :)

## Sanity Checks
- [ ] - The title of this pull request clearly describes the change I would like to make.
- [ ] - If there are multiple changes in this pull request, they are all related.
- [ ] - I have tried to write clear a commit message(s) that describes the changes I made.

2023-05-26 20:19 UTC, nullopt requested changes

2023-05-26 20:19 UTC, nullopt commented on dpm-advice/dpm-advice-basic/dpm-advice-basic-melee.txt
> +    •  <:fbackhand:535532879346794516> <:gflurry:535532879283879977> <:quake:535532879506309150>
Has two spaces after bullet

2023-05-26 20:19 UTC, nullopt commented on dpm-advice/dpm-advice-basic/dpm-advice-basic-melee.txt
>          - <:dragonriderlance:643161541931171872> auto attacks once every 3.6s (6t)
Needs consistent '.' usage at end of lines

2023-05-26 20:19 UTC, nullopt commented on dpm-advice/dpm-advice-basic/dpm-advice-basic-melee.txt
>  **__Sample Auxiliary Comboes__**
Comboes -> Combos according to Cambridge Dictionary

2023-05-26 20:19 UTC, nullopt commented on dpm-advice/dpm-advice-basic/dpm-advice-basic-melee.txt
>  ⬥ Deal higher damage
Consistent '.' usage

2023-05-26 20:19 UTC, nullopt commented on dpm-advice/dpm-advice-basic/dpm-advice-basic-melee.txt
>  ⬥ Provide a longstanding buff
Consistent '.' usage

2023-05-27 11:50 UTC, nullopt requested changes

2023-05-27 11:50 UTC, nullopt commented on dpm-advice/dpm-advice-basic/dpm-advice-basic-melee.txt
>  ⬥ Sacrifice adrenaline (-15%)
Missing a `.` here

2023-05-27 11:50 UTC, nullopt commented on dpm-advice/dpm-advice-basic/dpm-advice-basic-melee.txt
>          - <:dragonriderlance:643161541931171872> auto attacks once every 3.6s (6t)
And on these two lines here

2023-07-13 17:39 UTC, Sky-Justice reviewed
Formatting changes for dpm-advice-basic-melee

2023-07-15 17:12 UTC, Ferroric commented
Resolved all conflicts, may need to revisit after merging for any other small issues

2023-07-15 17:12 UTC, merged